[package]
name = "weld-bin"
version = "0.1.4"
edition = "2018"
authors = [ "wasmcloud Team" ]
license = "Apache-2.0"
description = "CLI for smithy model code generator and related tools"
homepage = "https://github.com/wasmcloud/weld"
repository = "https://github.com/wasmcloud/weld"
readme = "README.md"

[[bin]]
name = "weld"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
atelier_core = "0.2"
atelier_json = "0.2"
bytes = "1.0"
cargo_atelier = "0.2"
cargo_toml = "0.9"
clap = { version = "3.0.0-beta.2", features = ["derive"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dependencies.weld-codegen]
version = "0.1"
#path = "../codegen"
