[package]
name = "hello_send"
version = "0.1.0"
authors = [ "wasmcloud Team" ]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
console_log = "0.2"
futures = "0.3"
form_urlencoded = "1.0"
wasmcloud-example-httpserver = { path = "../../interface/http-server/rust" }
wasmcloud-example-hello = { path = "../../interface/hello/rust" }
log = "0.4"
serde_bytes = "0.11"
serde_json ="1.0"
serde = {version = "1.0", features = ["derive"]}

[dependencies.wasmbus-rpc]
version = "0.1"
path = "../../../rpc-rs"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
