[package]
name = "wasmcloud-provider-kvredis"
version = "0.2.0"
edition = "2018"
resolver = "2"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
crossbeam="0.8"
futures = "0.3"
log = "0.4"
once_cell = "1.8"
redis = {version = "0.21", features = ["tokio-comp"] }
rmp-serde = "0.15"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"

[dependencies.wasmcloud-interface-keyvalue]
version = "0.2"
#path = "../../interfaces/keyvalue/rust"

[dependencies.wasmbus-rpc]
version = "0.3"
#path = "../../weld/rpc-rs"

# test dependencies
[dev-dependencies]
anyhow = "1.0"
linkme = "0.2"
shuttle = "0.0.6"
termion = "1.5.6"

[dev-dependencies.wasmcloud-test-util]
version = "0.1"
#path = "../../wasmcloud-test/wasmcloud-test-util"

[[bin]]
name = "kvredis"
path = "src/main.rs"
