language: rust
services: docker
before_install:
- docker pull minio
- docker run -p 9000:9000 minio/minio -d server /data
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
fast_finish: true
