[package]
name = "wascc-httpsrv"
version = "0.3.2"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = "0.3.2"
actix-web = "1.0.9"
actix-multipart = "0.1.4"
futures = "0.1.29"
log = "0.4.8"
env_logger = "0.7.1"
crossbeam-channel = "0.4.0"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
prost-types = "0.5.0"
prost = "0.5.0"
bytes = "0.4.12"