[workspace]
members = [
    "bin",
    "codegen",
    "macros",
    "rpc-rs",
    "examples/interface/hello/rust",
    "examples/interface/rangekv/rust",
    "examples/interface/http-server/rust",
]

exclude = [
    # actors need to be excluded because they have different target configurations
    # we build them with 'make' instead
    "examples/actor",
    "examples/provider",
    "scratch",
]
