[package]
name = "wascc-httpsrv"
version = "0.4.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = "0.5.0"
actix-web = "1.0.9"
actix-rt = "0.2.4"
actix-multipart = "0.2.0"
futures = "0.1.29"
log = "0.4.8"
env_logger = "0.7.1"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"

