[package]
name = "redis-provider"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.7.1"
lazy_static = "1.4.0"
crossbeam-channel = "0.4.0"
crossbeam = "0.7.3"
crossbeam-utils = "0.7.0"
log = "0.4.8"
wascc-codec = "0.3.3"
prost-types = "0.5.0"
prost = "0.5.0"
bytes = "0.4.12"
redis = "0.13.0"