[package]
<<<<<<< HEAD
name = "wascc-redis-provider"
=======
name = "wascc-redis"
>>>>>>> c3cf76022150221eb4f1627c3155a4b6a6a53ea0
version = "0.6.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
repository = "https://github.com/wascc/redis-provider"
description = "Redis capability provider for the waSCC wasm host runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wascc-host"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wascc", "redis"]
<<<<<<< HEAD
categories = ["wasm", "api-bindings","command-line-utilities"]
=======
categories = ["wasm", "api-bindings"]
>>>>>>> c3cf76022150221eb4f1627c3155a4b6a6a53ea0

[badges]
maintenance = { status = "actively-developed" }

[features]
# Enable if the provider will be statically compiled into a host
static_plugin = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.7.1"
lazy_static = "1.4.0"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "0.7.2"
log = "0.4.8"
<<<<<<< HEAD
#wascc-codec = "0.5.0"
wascc-codec = { path = "../wascc-codec" }
=======
wascc-codec = "0.6.0"
>>>>>>> c3cf76022150221eb4f1627c3155a4b6a6a53ea0
redis = "0.15.1"