[package]
name = "wascc-telnet"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# Enable if the provider will be statically compiled into a host
static_plugin = []


[dependencies]
wascc-codec = "0.6.0"
log = "0.4.8"
env_logger = "0.7.1"
telnet = "0.1.4"
ansi-escapes = "0.1.0"
uuid = { version = "0.8", features = ["serde", "v4"]}
crossbeam = "0.7.3"
crossbeam-channel = "0.4.2"
serde = "1.0.110"
serde_derive = "1.0.110"