[package]
name = "nats-provider"
version = "0.1.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = "0.3.4"
log = "0.4.10"
env_logger = "0.7.1"
crossbeam-channel = "0.4.0"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
prost-types = "0.5.0"
natsclient = "0.0.5"
prost = "0.5.0"