# codegen.toml
# ensures that src/wasmbus_model.rs is up-to-date

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-core-interface-v0.2.0/core/wasmcloud-core.smithy"
[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@wasmcloud-model-interface-v0.2.0/core/wasmcloud-model.smithy"

[rust]
output_dir = "."

[[rust.files]]
path = "src/wasmbus_model.rs"
namespace = "org.wasmcloud.model"
