# rustfmt prefs
#

edition = "2021"

# wrap string literals that exceed max_width
format_strings = true

# tidy imports- group by crate
imports_granularity = "Crate"

# consistent ordering of trait (type and const first, then macros and methods)
reorder_impl_items = true

