# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # must be on a port accessible to the capability provider
      - 127.0.0.1:5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 127.0.0.1:9999:80

#  adminer:
#    image: adminer
#    env_file:
#    - .env
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  pgdata:
