[package]
name = "wasmcloud-examples-provider-hello"
version = "0.1.1"
authors = [ "wasmcloud Team" ]
edition = "2018"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmcloud/weld"
description = "Hello-world example capability provider"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-example-provider-hello"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasmcloud", "example"]
categories = ["wasm", "api-bindings"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
crossbeam="0.8"
chrono = "0.4"
once_cell = "1.8"
pretty_env_logger = "0.4"
log = "0.4"
nats = "0.9"
rmp-serde = "0.15"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[dependencies.wasmcloud-example-hello]
version = "0.1"
path = "../../interface/hello/rust"

[dependencies.wasmbus-rpc]
version = "0.1"
#path = "../../../rpc-rs"
