# This defines the projects that will be loaded with project.exs

actors = [ "hello_send" ]
providers = [ "httpserver", "hello" ]

# link hello actor with httpserver
[[links]]
actor="hello_send"
contract="wasmcloud:httpserver"
params= { PORT = "8080" }

# link hello actor with hello provider
[[links]]
actor="hello_send"
contract="wasmcloud:example:hello"
params= {}

