
# model sources and dependencies
[[models]]
#url = "https://wasmcloud.github.io/models/org.wasmcloud"
path = "../models/smithy"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]
#[[models]]
#files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

##
## Rust Codegen
##
[rust]
# output dir relative to OUT_DIR (compiler environment variable)
output_dir = "src"

## parameters for codegen
[rust.parameters]


[[rust.files]]
namespace = "org.wasmcloud.core"
path = "core.rs"
crate = "wasmbus_rpc"
