[package]
name = "graphguest"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasccgraph-common = { path = "../common" }
wascc-actor = "0.7.1"
