[package]
name = "wasmcloud-example-httpserver"
version = "0.1.0"
#description = ""
authors = [ "wasmcloud Team" ]
edition = "2018"
license = "Apache-2.0"
exclude = [ "build.rs" ]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["guest"]
guest = []

[dependencies]
async-trait = "0.1"
serde = { version = "1.0" , features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
lazy_static = "1.4"

[dependencies.wasmbus-rpc]
version = "0.1"
path = "../../../../rpc-rs"

[dev-dependencies]
base64 = "0.13"

[build-dependencies.weld-codegen]
version = "0.1"
path = "../../../../codegen"
