name: provider-archive

on:
  push:
    branches: [ main ]
    tags:
    - 'provider-archive-v*'
  pull_request:
    branches: [ main ]
    paths:
    - "Cargo.lock"
    - "Cargo.toml"
    - "crates/provider-archive"
    - "flake.lock"
    - "flake.nix"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./crates/provider-archive

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}

  release-crate:
    if: startswith(github.ref, 'refs/tags/provider-archive-v') # Only run on tag push
    needs: [cargo_check, clippy_check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify 
        working-directory: ${{ env.working-directory }}
