name: wascap

on:
  push:
    branches: [ main ]
    tags:
    - 'wascap-v*'
  pull_request:
    branches: [ main ]
    paths:
    - "Cargo.lock"
    - "Cargo.toml"
    - "crates/wascap"
    - "flake.lock"
    - "flake.nix"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./crates/wascap

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}

  release-crate:
    if: startswith(github.ref, 'refs/tags/wascap-v') # Only run on tag push
    needs: rust_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: crates-release-action
        uses: wasmcloud/common-actions/crates-release@main
        with:
          working-directory: ${{ env.working-directory }}
          crates-token: ${{ secrets.CRATES_PUBLISH_TOKEN }}
