name: WASMCLOUD-CONTROL-INTERFACE

on:
  push:
    branches: [ main ]
    paths:
    - "rust/**"
  pull_request:
    branches: [ main ]
    paths:
    - "rust/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./rust

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: rust-check-action
      uses: wasmcloud/common-actions/rust-check@main
      with:
        working-directory: ${{ env.working-directory }}
