name: WASMCLOUD-CONTROL-INTERFACE_RELEASE

on:
  push:
    tags:
    - 'wasmcloud-control-interface-v*'

env:
  CARGO_TERM_COLOR: always
  working-directory: ./rust

jobs:
  rust_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: rust-check-action
      uses: wasmcloud/rust-check-action@v1rc1
      with:
        working-directory: ${{ env.working-directory }}

  github_release:
    needs: [rust_check]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify
        working-directory: ${{ env.working-directory }}
